FROM openjdk:17-slim
WORKDIR /app

ENV JAVA_OPTS="-Xms256m -Xmx2G -XX:+ExitOnOutOfMemoryError  -Djava.security.egd=file:///dev/./urandom -Dsecurerandom.source=file:///dev/./urandom"

ARG JAR_FILE
ARG OC_ACC_FILE
COPY ${JAR_FILE} app.jar
COPY ${OC_ACC_FILE} oc_acc.csv


ENTRYPOINT ["sh", "-c", "java ${JAVA_OPTS} -jar app.jar ${0} ${@}"]#